optimizer : GRADIENT_DESCENT
stopcondition {
  all_processed: false
  #steps: 2000000
  steps: 100000
}
train: true 
batchsize: 128
data_proto: "../data/cifar10_kmeans.pbtxt"
eval_after: 10000
checkpoint_after: 10000
checkpoint_directory: "../models"
show_after: 0
randomize: true
verbose: true
#get_last_piece: true
